# Generated by Django 5.0.7 on 2024-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsdapp', '0003_alter_friendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='fsdapp.profile'),
        ),
    ]
