# Generated by Django 5.0.7 on 2024-07-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsdapp', '0007_remove_friendrequest_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='fsdapp.profile'),
        ),
    ]
