# Generated by Django 5.0.7 on 2024-07-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsdapp', '0011_alter_profile_profile_photo_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('education', 'Education'), ('job', 'Job'), ('news', 'News'), ('shopping', 'Shopping'), ('mixed', 'Mixed'), ('friends', 'Friends'), ('kids', 'Kids')], default='entertainment', max_length=50),
        ),
    ]
