# Generated by Django 5.0.7 on 2024-07-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsdapp', '0013_post_link_alter_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='to_user',
        ),
    ]
