# Generated by Django 5.0.7 on 2024-07-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsdapp', '0002_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
