# Generated by Django 5.0.7 on 2024-07-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsdapp', '0006_alter_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='ignored',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
            preserve_default=False,
        ),
    ]
